- name: Install remote.it CLI
  shell: pwsh
  run: |
    try {
      curl -L -o remoteit.zip https://downloads.remote.it/cli/remoteit-win.zip
      New-Item -ItemType Directory -Path "$env:USERPROFILE\remoteit" -Force
      Expand-Archive -Path "remoteit.zip" -DestinationPath "$env:USERPROFILE\remoteit"
      Set-Location "$env:USERPROFILE\remoteit"
      Get-ChildItem  # kiểm tra file giải nén

      .\remoteit.exe login --username "${{ secrets.REMOTEIT_USERNAME }}" --password "${{ secrets.REMOTEIT_PASSWORD }}"
      .\remoteit.exe register --name "${{ secrets.DEVICE_NAME }}" --port 3389
      .\remoteit.exe connect --name "${{ secrets.DEVICE_NAME }}" --port 3389"
    } catch {
      Write-Host "ERROR: $($_.Exception.Message)"
      exit 1
    }
